digite = input('Digite algo:')
print('O tipo primitivo desse valor é {}'.format(type(digite)))
print('Só tem espaços? {}'.format(digite.isspace()))
print('É um número? {}'.format(digite.isnumeric()))
print('É alfabético? {}'.format(digite.isalpha()))
print('É alfanumérico? {}'.format(digite.isalnum()))
print('Ésta em maiúsculas? {}'.format(digite.isupper()))
print('Ésta em minúsculas? {}'.format(digite.islower()))
print('Ésta capitalizadas? {}'.format(digite.istitle()))
